########
# pd-glry
#

TOP := ..
include $(TOP)/build/def.mk
$(call expand_dep_jar, $(TOP)/common)

LOCAL_MODULE  := pd-glry
LOCAL_PACKAGE := th.pd.glry
LOCAL_SRC_DIR := ./src
LOCAL_RES_DIR := ./res
include $(TOP)/build/apk.mk
