########
# pd-mail
#

TOP := ..
include $(TOP)/build/def.mk
$(call expand_dep_jar, $(TOP)/common)

LOCAL_MODULE := pd-mail
LOCAL_PACKAGE := th.pd.mail
LOCAL_SRC_DIR := ./src
LOCAL_RES_DIR := ./res
include ../build/apk.mk
