########
# pd-fmgr
#

TOP := ..
include $(TOP)/build/def.mk
$(call expand_dep_jar, $(TOP)/common)

LOCAL_MODULE := pd-fmgr
LOCAL_PACKAGE := th.pd.fmgr
LOCAL_SRC_DIR := ./src
LOCAL_RES_DIR := ./res
include ../build/apk.mk
